# Используем официальный образ Go
FROM golang:latest

# Устанавливаем рабочую директорию
WORKDIR /app

# Копируем файлы зависимостей
COPY go.mod go.sum ./
RUN go mod download

# Копируем исходный код
COPY . .

# Сборка приложения
RUN go build -o /app/main ./cmd/app/main.go


# Указываем порт приложения
EXPOSE 8080

# Запуск приложения
CMD ["/app/main"]
